version: '3'

services:
  nginx:
# container-name: nginx
    build: ./requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    restart: on-failure

networks:
  inception:
    name: inception
    driver: bridge