version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    # image: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress-vol:/var/www/wordpress
    networks:
      - inception
    restart: on-failure

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    # image: mariadb
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - mariadb-vol:/var/lib/mysql
    networks:
      - inception
    restart: on-failure
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    # image: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wordpress-vol:/var/www/wordpress
    networks:
      - inception
    restart: on-failure

volumes:
  mariadb-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PATH_DATA}/mariadb-data
  wordpress-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${PATH_DATA}/wordpress-data

networks:
  inception:
    name: inception
    driver: bridge